I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    suspect1 "Yo no fui. Estaba en la biblioteca cuando ocurrió el asesinato."
Exception: Sayer 'suspect1' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    suspect1 "Yo no fui. Estaba en la biblioteca cuando ocurrió el asesinato."
  File "C:\Users\alleg\Desktop\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\alleg\Desktop\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\alleg\Desktop\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'suspect1' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
novela policial 1.0
Wed Feb 12 12:41:52 2025
